### ISSUE TITLE
Unit testing run stopped working on version 2.105.0

### ISSUE THREAD

**Issue by hotavianom** [vtex/toolbelt#897]
## Expected Behavior
$ vtex test unit

And run unit tests in the project

## Current Behavior

Instead of run the tests I get this:
```
➜  bank-messages git:(master) vtex test unit
15:57:33.380 - error: Unhandled exception  
15:57:33.381 - error: Please report the issue in https://github.com/vtex/toolbelt/issues  
15:57:33.381 - error: Raw error: vtex_1.getManifest is not a function TypeError: vtex_1.getManifest is not a function
    at Object.exports.default (/Users/hotaviano/.config/yarn/global/node_modules/@vtex/cli-plugin-test/build/modules/apps/testCommand.js:62:35)
    at async UnitTest.run (/Users/hotaviano/.config/yarn/global/node_modules/@vtex/cli-plugin-test/build/commands/test/unit.js:10:9)
    at async UnitTest._run (/Users/hotaviano/.config/yarn/global/node_modules/vtex/build/api/oclif/CustomCommand.js:25:28)
    at async Config.ctx.config.runCommand (/Users/hotaviano/.config/yarn/global/node_modules/@tiagonapoli/oclif-plugin-spaced-commands/lib/hooks/init.js:89:9)
    at async Main.run (/Users/hotaviano/.config/yarn/global/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/Users/hotaviano/.config/yarn/global/node_modules/@oclif/command/lib/command.js:43:20)  
15:57:33.389 - error: ErrorID: 672d43f6015d1b9d67c8aac863378201
```

## Steps to Reproduce (for bugs)

1. Make sure the toolbelt version is v2.105.0
2. run: `vtex test unit`

## Context

Just trying to run unit tests.

## Your Environment

* Version used: vtex/2.105.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node-v12.18.2
* Operating System and version (desktop or mobile): desktop

**Comment by tiagonapoli** [comment]
Thanks for the report! This issue is solved on the latest version, if the problem continues feel free to reopen
